---
openapi: 3.0.3
x-apiname: accounts # comment out to show warning
x-responsetime: 1000 # comment out to show warning
info:
  title: Accounts
  description: "API for managing accounts."
  version: 1.0.0
  contact:
    email: "admin@admin.com"
    url: "http://www.postman.com"
  termsOfService: https://example.com/tos
  license:
    name: BSD-1-Clause
    url: https://opensource.org/license/bsd-1-clause

servers:
  - url: "http://localhost:3000"
  - url: "http://localhost:3001"

paths:
  "/accounts":
    get:
      summary: Get accounts
      description: "Get all from the API at the / endpoint"
      operationId: getAccounts
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Security'
                type: object
                properties:
                  message:
                    type: string
                    example: You made a GET request!
              examples:
                Success:
                  value:
                    message: You made a GET request!
        "500":
          description: Internal server error
    put:
      summary: Replace an account entry
      description: "Put data at the / endpoint by passing a query parameter representing the id and body json with the data to update with"
      operationId: replaceAnAccountEntry
      parameters:
        - name: id
          description: placeholder description
          example: 1234-4321-1234-4321
          in: query
          schema:
            $ref: '#/components/schemas/Security'
            type: string
            example: ut
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Security'
              type: object
              properties:
                name:
                  type: string
                  example: Duis ex pariatur
            example:
              name: Duis ex pariatur
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Security'
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: sue
                  message:
                    type: string
                    example: You made a PUT request to update id=1 with the following data!
              examples:
                OK:
                  value:
                    data:
                      name: sue
                    message: You made a PUT request to update id=1 with the following data!
        "500":
          description: Internal server error
    post:
      summary: Add new account
      description: "Post data to the API at the / endpoint, passing the json to add as body data"
      operationId: addNewAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Security'
              type: object
              properties:
                location:
                  type: string
                  example: sunt anim irure occaecat
                name:
                  type: string
                  example: veniam laboris sit quis
            example:
              location: sunt anim irure occaecat
              name: veniam laboris sit quis
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Security'
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      location:
                        type: string
                        example: United Kingdom
                      name:
                        type: string
                        example: sue
                  message:
                    type: string
                    example: You made a POST request with the following data!
              examples:
                Created:
                  value:
                    data:
                      location: United Kingdom
                      name: sue
                    message: You made a POST request with the following data!
        "500":
          description: Internal server error
    delete:
      summary: Delete an account
      description: "Delete data from the API at the / endpoint, specifying the data by passing its id as a query parameter"
      operationId: deleteAnAccount
      parameters:
        - name: id
          description: placeholder description
          example: 1234-4321-1234-4321
          in: query
          schema:
            $ref: '#/components/schemas/Security'
            type: string
            example: ut
      responses:
        "204":
          description: Success
        "500":
          description: Internal server error
    patch:
      summary: Update an account
      description: "Patch data at the / endpoint by passing a query parameter representing the id and body json with the data to update with"
      operationId: updateAnAccount
      parameters:
        - name: id
          description: placeholder description
          example: 1234-4321-1234-4321
          in: query
          schema:
            $ref: '#/components/schemas/Security'
            type: string
            example: ut
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Security'
              type: object
              properties:
                name:
                  type: string
                  example: Duis ex pariatur
            example:
              name: Duis ex pariatur
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Security'
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: sue
                  message:
                    type: string
                    example: You made a PATCH request to update id=1 with the following data!
              examples:
                Success:
                  value:
                    data:
                      name: sue
                    message: You made a PATCH request to update id=1 with the following data!
        "500":
          description: Internal server error
tags: []

components:
  securitySchemes:
    apiKey:
      type: http
      scheme: basic
  schemas:
    Security:
      type: object

security:
  - apiKey: []